name: inapp_purchase
description: A new Flutter package project.
version: 2.0.0
homepage: https://github.com/cassiomeira12/inapp_purchase

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  in_app_purchase: 3.0.7
  package_info: 2.0.2
  url_launcher: 6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
